### ISSUE TITLE
Va mal el p115

### ISSUE THREAD

**Issue by sermo18** [patxisldaw19/programame#31]
1 no tiene Scanner sc = new Scanner(System.in); esta linea.
2 falta un ; en String scuadrado = Long.toString(cuadrado)
3  if (der.equals(""')){ sobra esta comilla '
4 en la linea 49 hay un } que no cierra nada, bajo de f++;
5 la variable izq no esta inicializada

**Comment by patxisldaw19** [comment]
Arreglado
