### ISSUE TITLE
Soluciones para tu problema 115

### ISSUE THREAD

**Issue by Luciano-Daw** [patxisldaw19/programame#39]
Para empezar, hay problemas sintácticos cono en la linea 18.
En la linea 37, hay errores sintácticos, para comparar mirate esta página que te servirá de ayuda http://www.w3api.com/wiki/Java:String.equals()

**Comment by Luciano-Daw** [comment]
olvida lo que he puesto del 50 al 56, utiliza esta opción:
if(esKaprekar){
			System.out.println("SI.");
		}
		else {
			System.out.println("NO.");
		}
}

**Comment by Luciano-Daw** [comment]
esto pasa porque no estaban las llaves bien puestas

**Comment by Luciano-Daw** [comment]
Sobra la linea del comentario por abajo.

**Comment by patxisldaw19** [comment]
Solucionado
